Added command GOTO <pose> in Actions Rendering Engine
robotology/icub-main pull request #705
Opened 2020-12-16 09:50 UTC by Iaxama

With this PR the ARE accepts a new command which allows to move the robot to a specific pose. The possible poses can be added in the corresponding ini file and referenced using a tag.

2020-12-16 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/robotology/icub-main?pullRequest=705) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/robotology/icub-main?pullRequest=705) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/robotology/icub-main?pullRequest=705) it.</sub>

2020-12-18 10:13 UTC, Nicogene requested changes

2020-12-18 10:13 UTC, Nicogene commented on app/yarpmanager/conf/cluster-config.xml
> +<node>icub-cuda</node>
I suppose that this file has been added by mistake, the `cluster-config.xml` should be a template to configure for each cluster

2020-12-18 10:13 UTC, pattacini commented
Hi @Iaxama 

Although I can clearly see the effort you put into this work, I feel this PR proposes changes that are rather off-topic in the ARE context.

ARE was born to provide a sort of high-level wrapper capable of executing **coordinated actions in the Cartesian space**, meaning actions that involve different parts (arms, head, fingers) in the operational domain in a given sequential way.

It seems to me that the control of parts in the joint space can be achieved using other standard tools we usually employ as, for example, the combination of [**`ctpService`**][1] and **bash scripts** (take a look at the bunch of scripts available in [`robotology/funny-things/app/scripts/shells`][2]). This combination works great and lies at the heart of the infrastructure we use to run demos for experiments as well as TV shows.

I've tried above to detail out the main reason why I believe this PR doesn't fit with the current architecture, but please consider also the points below:
- ARE has been growing like a monolithic beast and the central idea is to freeze it and start off following a very different development roadmap, more modular, more effective.
- Managing yet another database of actions within ARE turns to be quite overlapping and cumbersome (yep, there exists already one).
- Better off resorting to ARE only for complex sequential actions and use other tools/modules for simpler movements. Here's a list of components belonging to the `icub-main` bundle:
  - `ctpService`
  - `cartesianInterfaceControl`
  - `wholeBodyPlayer` 

[1]: https://robotology.github.io/robotology-documentation/doc/html/group__ctpService.html
[2]: https://github.com/robotology/funny-things/tree/master/app/scripts/shells

2020-12-18 10:27 UTC, pattacini commented
A few other minor points @Iaxama:
- you may consider signing up the [CLA][1] to be ready for further contributions.
- we tend to use the term `pose` for 6D goals of the end-effector, whereas we tend to use the `term` configuration to identify the joints' values.

[1]: https://github.com/robotology/icub-main/pull/705#issuecomment-746006070

2020-12-20 10:46 UTC, pattacini commented
Somehow related to https://github.com/robotology/QA/discussions/454.

2020-12-24 13:58 UTC, closed without merging