Update `serviceParser` + `eomcParser` + `embObjMotionControl` to support `amcbldc` boards in xml files
robotology/icub-main pull request #832
Opened 2022-10-04 15:45 UTC by sgiraz

What's new:

- the `parse2FocGroup` has been renamed to `parseFocGroup` and it has been extended to include the `groupName` param valid for either `2FOC` and `AMCBLDC`
- rename `twofocinfo` to `foc_based_info` to be compliant with the meaning of `foc-based`
- removed unused `iMange2focBoards` function
- save the board type in `ServiceParser::parseService`
- minor cleanup of some old comments

**Notes**
- tested on `lego-setup`

cc @pattacini @valegagge @ale-git @mfussi66

2022-10-04 16:30 UTC, pattacini requested changes

2022-10-04 16:30 UTC, pattacini commented on conf/iCubFindDependencies.cmake
> +    message(FATAL_ERROR "An old version of icub-firmware-shared has been detected, but at least 1.28.1 is required")
Need to be `1.28.0`

2022-10-04 16:36 UTC, pattacini approved these changes

2022-10-05 10:56 UTC, marcoaccame approved these changes
seems fine by me

2022-10-05 11:07 UTC, pattacini commented
Awaiting the CI to complete before merging.

2022-10-05 11:40 UTC, merged