Bugfix `kbemf` set to 0 by default when not found
robotology/icub-main pull request #935
Opened 2024-01-22 13:40 UTC by sgiraz

This PR enables the `eomcParser` to parse all parameters within `TRQ_PID_OUTPUT_CURR`, even if `kbemf` is missing.

cc @pattacini @Nicogene @isorrentino @DanielePucci

2024-01-22 13:41 UTC, DanielePucci commented
Cc @GiulioRomualdi

2024-01-22 13:48 UTC, pattacini requested changes
Thanks heaps for the fix @sgiraz 
Just one inline comment to address.

2024-01-22 13:48 UTC, pattacini commented on src/libraries/icubmod/embObjMotionControl/eomcParser.cpp
> +        for (int j = 0; j<_njoints; j++) _kbemf[j] = 0;
We should print a warning here.

2024-01-22 14:06 UTC, pattacini approved these changes
Thanks!
Awaiting the CI before merging.

2024-01-22 14:51 UTC, merged

2024-01-24 08:40 UTC, randaz81 commented
Is kbemf not used anymore? Then it's ok to have a default = 0. Otherwise I'd like to say that's a bad software practice to mix mandatory with optional parameters in the same parser block. In the long term things get confused, undocumented and In the past I have seen default value changing without any notice, leading to difficult-to-debug situations. For this reason, at least in yarp, the use default parameters is generally discouraged, and a revision of the configuration files to add the missing parameter is preferred.

2024-01-24 08:43 UTC, pattacini commented
Hi @randaz81 

> Is kbemf not used anymore? Then it's ok to have a default = 0.

Indeed, `kbemf` is deprecated and already removed from the config files as per https://github.com/robotology/robots-configuration/pull/599.