Add MotorTemperaturePublisher tool
robotology/icub-main pull request #951
Opened 2024-03-11 14:23 UTC by MSECode

Add to `src/tools` a new tool called `motorTemperaturePublisher` which might be helpful for publishing the motor temperatures read from the ETH callback on the software. As things now the module can be started and used on a single robot subpart at the same time. So, if you need to check the temperature of multiple subparts or you start multiple instances of the application or you change the `app/conf/config.ini` file each time defining under `portprefix` the subpart that you need and in `listofjoints` the list of the jonts you desire to read the temperature. 

All other specific info about what the module does and how to build it can be found in the `README.md`

2024-03-11 15:24 UTC, pattacini requested changes
Some points to address:
- Missing copyright in the code files.
- App files need to be moved to `icub-main/app`. Get inspired by how it's done from one example there.
- We don't use README but rather doxygen to publish [documentation](https://robotology.github.io/robotology-documentation/doc/html/).
  - See for example: https://github.com/robotology/icub-main/blob/devel/src/modules/motionCUT/motionCUT.xml.
- We also need to account for the new addition by extending the `src/tools/CMakeLists.txt` file.

2024-03-11 15:24 UTC, pattacini commented on src/tools/motorTemperaturePublisher/CMakeLists.txt
> +install(TARGETS ${PROJECT} DESTINATION bin)
```suggestion
install(TARGETS ${PROJECT_NAME} DESTINATION bin)
```

2024-03-11 15:24 UTC, pattacini commented on src/tools/motorTemperaturePublisher/CMakeLists.txt
> +find_package(YARP REQUIRED)
Better off narrowing down what you need. Something like:
```cmake
find_package(YARP COMPONENTS os sig dev math)
```

2024-03-11 15:24 UTC, pattacini commented on src/tools/motorTemperaturePublisher/CMakeLists.txt
> +install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/app/conf/config.ini DESTINATION ${YARP_CONTEXTS_INSTALL_DIR}/${PROJECT_NAME})
This shouldn't be here as app files must go to `icub-main/app`.

2024-03-11 15:24 UTC, pattacini commented on src/tools/motorTemperaturePublisher/README.md
We don't use README files.

2024-03-12 09:35 UTC, MSECode commented on src/tools/motorTemperaturePublisher/CMakeLists.txt
> +find_package(YARP COMPONENTS os sig dev math)
also `dev` I need

2024-03-14 15:07 UTC, pattacini commented on src/tools/motorTemperaturePublisher/CMakeLists.txt
> +project(MotorTemperaturePublisher)
```suggestion
# Copyright: (C) 2024 iCub Facility - Istituto Italiano di Tecnologia
# Authors: Jacopo Losi
# CopyPolicy: Released under the terms of the GNU GPL v2.0.

project(MotorTemperaturePublisher)
```

CMake is also code, actually.

2024-03-14 16:35 UTC, pattacini requested changes
The very last point is to extend this CMakeLists.txt file:
- https://github.com/robotology/icub-main/blob/master/app/CMakeLists.txt

2024-03-15 07:27 UTC, pattacini approved these changes

2024-03-15 07:27 UTC, merged