Add `couplingICubEye` device
robotology/icub-main pull request #997
Opened 2024-12-02 15:47 UTC by martinaxgloria

This pull request introduces the new `couplingICubEye` coupling handler device.
Need to test it
It implements the IJointCoupling interface:
- https://github.com/robotology/yarp/pull/3026

2024-12-02 16:09 UTC, pattacini commented
We have to get aligned on the name as the Eyes Mk3 do refer to an internal experiment that is obsolete.
Also, Mk2 and Mk4 do have essentially the same mechanism with tiny different kinematic params.

2024-12-18 13:47 UTC, Nicogene commented
This PR has been tested with:
- https://github.com/robotology/icub-models/pull/249
- #995  

@pattacini  @traversaro  it is ready to be reviewed/merged

2024-12-18 13:57 UTC, traversaro approved these changes
Minor comments.

2024-12-18 13:57 UTC, traversaro commented on src/libraries/icubmod/couplingICubEye/CouplingICubEye.h
> +/** TBD
Leftover?

2024-12-18 14:11 UTC, Nicogene approved these changes
Tested together!

2024-12-18 14:12 UTC, Nicogene commented
> Is the device on by default? If not, could it make sense to enable it by default or add it to the default preset?

Yes it is enabled by default, it does not have external dependencies except YARP

2024-12-18 14:40 UTC, pattacini requested changes
Hi @Nicogene @martinaxgloria 

Could you please address the conflicts?

2024-12-18 16:00 UTC, pattacini approved these changes
Awaiting the CI before merging.

2024-12-18 16:32 UTC, merged